services:
   api:
      image: dlanuza-2022/nextops.api:latest
      container_name: nextops_api
      restart: always
      ports:
         - "5000:8080"
      environment:
         - ASPNETCORE_ENVIRONMENT=Production
         - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=nextops_db;Username=postgres;Password=Admin123!
      depends_on:
         - db

   db:
      image: postgres:16-alpine
      container_name: nextops_postgresdb
      restart: always
      environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: Admin123!
         POSTGRES_DB: nextops_db
      ports:
         - "5432:5432"
      volumes:
         - pg_data:/var/lib/postgresql/data

volumes:
   pg_data:
